import datetime
import html
import re
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, XPreformatted, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from backend.models import Scan, Project, Vulnerability

def safe_escape(val) -> str:
    if val is None:
        return ""
    return html.escape(str(val))

def mask_secret(secret_str: str) -> str:
    if not secret_str:
        return "********"
    s = secret_str.strip()
    if len(s) <= 8:
        return s[:2] + "****" + s[-2:]
    return s[:3] + "***************" + s[-4:]

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        
        # Header (Pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "AI BUG HUNTER  |  ENTERPRISE SECURITY ASSESSMENT REPORT")
            self.setStrokeColor(colors.HexColor("#06b6d4"))
            self.setLineWidth(1)
            self.line(54, 742, 558, 742)
            
        # Footer (All Pages)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_str)
        self.drawString(54, 36, "Generated by AI Bug Hunter  •  AI-Powered Defensive Security & Vulnerability Analysis")
        self.setStrokeColor(colors.HexColor("#1e293b"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        
        self.restoreState()


def generate_pdf_report(scan: Scan, project: Project, vulnerabilities: list, output_path: Path):
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )

    styles = getSampleStyleSheet()
    
    # Palette
    c_navy_bg = colors.HexColor("#050816")
    c_cyan = colors.HexColor("#06b6d4")
    c_violet = colors.HexColor("#8b5cf6")
    c_red = colors.HexColor("#ef4444")
    c_orange = colors.HexColor("#f97316")
    c_yellow = colors.HexColor("#eab308")
    c_blue = colors.HexColor("#3b82f6")
    c_green = colors.HexColor("#10b981")
    c_dark_card = colors.HexColor("#0f172a")
    c_border = colors.HexColor("#1e293b")
    c_text_muted = colors.HexColor("#64748b")
    c_text_dark = colors.HexColor("#0f172a")
    c_text_body = colors.HexColor("#334155")

    # Typography Styles
    title_style = ParagraphStyle(
        "CoverTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=26,
        leading=32,
        textColor=c_text_dark,
        alignment=0,
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        "CoverSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=c_cyan,
        spaceAfter=20
    )

    h1_style = ParagraphStyle(
        "Header1",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=c_text_dark,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )

    h2_style = ParagraphStyle(
        "Header2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        "BodyCustom",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=c_text_body,
        spaceAfter=6
    )

    code_style = ParagraphStyle(
        "CodeCustom",
        fontName="Courier",
        fontSize=8,
        leading=10,
        textColor=c_text_dark,
        backColor=colors.HexColor("#f8fafc"),
        borderColor=colors.HexColor("#cbd5e1"),
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=8
    )

    story = []

    # Calculate statistics & overall status
    critical_cnt = scan.critical_count or 0
    high_cnt = scan.high_count or 0
    medium_cnt = scan.medium_count or 0
    low_cnt = scan.low_count or 0
    total_cnt = scan.total_vulnerabilities or 0

    penalty = critical_cnt * 15 + high_cnt * 8 + medium_cnt * 3 + low_cnt * 1
    score = max(0, min(100, 100 - penalty))

    if score >= 85 and critical_cnt == 0 and high_cnt == 0:
        overall_status = "SECURE"
        status_color = c_green
    elif score >= 60 and critical_cnt == 0:
        overall_status = "AT RISK"
        status_color = c_yellow
    else:
        overall_status = "CRITICAL"
        status_color = c_red

    # Separate findings into Secrets, Dependencies, and General Code Vulns
    secrets_list = [v for v in vulnerabilities if "secret" in (v.category or "").lower() or "credential" in (v.category or "").lower() or v.tool_name == "Gitleaks"]
    deps_list = [v for v in vulnerabilities if "depend" in (v.category or "").lower() or "package" in (v.category or "").lower() or v.tool_name == "Dependency Analyzer"]
    sast_list = [v for v in vulnerabilities if v not in secrets_list and v not in deps_list]

    # --- 1. COVER / HEADER SECTION ---
    story.append(Spacer(1, 15))
    story.append(Paragraph("AI BUG HUNTER", ParagraphStyle("BrandTag", fontName="Helvetica-Bold", fontSize=10, leading=12, textColor=c_cyan)))
    story.append(Paragraph("Security Assessment Report", title_style))
    story.append(Paragraph("ENTERPRISE STATIC APPLICATION SECURITY TESTING (SAST) AUDIT", subtitle_style))
    
    # Metadata & Status Table
    meta_table_data = [
        [
            Paragraph("<b>Target Project:</b>", body_style), Paragraph(safe_escape(project.name), body_style),
            Paragraph("<b>Report ID:</b>", body_style), Paragraph(f"REP-{scan.id:05d}", body_style)
        ],
        [
            Paragraph("<b>Source / Upload Type:</b>", body_style), Paragraph(safe_escape((project.upload_type or "file").upper()), body_style),
            Paragraph("<b>Report Version:</b>", body_style), Paragraph("v2.4.0 (Enterprise)", body_style)
        ],
        [
            Paragraph("<b>Primary Language:</b>", body_style), Paragraph(safe_escape(project.language_detected or "Python"), body_style),
            Paragraph("<b>Scan Timestamp:</b>", body_style), Paragraph(safe_escape(scan.created_at.strftime('%Y-%m-%d %H:%M:%S UTC') if scan.created_at else "N/A"), body_style)
        ],
        [
            Paragraph("<b>Security Score:</b>", body_style), Paragraph(f"<b>{score} / 100</b>", ParagraphStyle("ScoreVal", parent=body_style, textColor=status_color, fontName="Helvetica-Bold")),
            Paragraph("<b>Overall Status:</b>", body_style), Paragraph(f"<b>{overall_status}</b>", ParagraphStyle("StatusVal", parent=body_style, textColor=status_color, fontName="Helvetica-Bold"))
        ]
    ]

    meta_table = Table(meta_table_data, colWidths=[110, 140, 110, 140])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 20))

    # --- 2. EXECUTIVE SUMMARY SECTION ---
    story.append(Paragraph("1. Executive Summary", h1_style))
    summary_body = (
        f"This automated security evaluation performed an in-depth static code analysis, hardcoded secret audit, "
        f"and dependency vulnerability assessment on target project <b>{safe_escape(project.name)}</b>. "
        f"A total of <b>{total_cnt} security findings</b> were identified across the codebase. "
        f"The system calculated an overall defensive <b>Security Score of {score}/100</b> resulting in a rating of <b>{overall_status}</b>."
    )
    story.append(Paragraph(summary_body, body_style))
    story.append(Spacer(1, 10))

    # Executive Summary Metrics Card Grid
    exec_grid_data = [
        [
            Paragraph("<b>Total Issues</b>", ParagraphStyle("C1", parent=body_style, fontName="Helvetica-Bold", alignment=1)),
            Paragraph("<b>Critical</b>", ParagraphStyle("C2", parent=body_style, fontName="Helvetica-Bold", textColor=c_red, alignment=1)),
            Paragraph("<b>High</b>", ParagraphStyle("C3", parent=body_style, fontName="Helvetica-Bold", textColor=c_orange, alignment=1)),
            Paragraph("<b>Medium</b>", ParagraphStyle("C4", parent=body_style, fontName="Helvetica-Bold", textColor=c_yellow, alignment=1)),
            Paragraph("<b>Low</b>", ParagraphStyle("C5", parent=body_style, fontName="Helvetica-Bold", textColor=c_blue, alignment=1)),
            Paragraph("<b>Secrets</b>", ParagraphStyle("C6", parent=body_style, fontName="Helvetica-Bold", alignment=1)),
            Paragraph("<b>Score</b>", ParagraphStyle("C7", parent=body_style, fontName="Helvetica-Bold", textColor=status_color, alignment=1)),
        ],
        [
            Paragraph(f"<b>{total_cnt}</b>", ParagraphStyle("V1", parent=body_style, fontSize=12, alignment=1)),
            Paragraph(f"<b>{critical_cnt}</b>", ParagraphStyle("V2", parent=body_style, fontSize=12, textColor=c_red, alignment=1)),
            Paragraph(f"<b>{high_cnt}</b>", ParagraphStyle("V3", parent=body_style, fontSize=12, textColor=c_orange, alignment=1)),
            Paragraph(f"<b>{medium_cnt}</b>", ParagraphStyle("V4", parent=body_style, fontSize=12, textColor=c_yellow, alignment=1)),
            Paragraph(f"<b>{low_cnt}</b>", ParagraphStyle("V5", parent=body_style, fontSize=12, textColor=c_blue, alignment=1)),
            Paragraph(f"<b>{len(secrets_list)}</b>", ParagraphStyle("V6", parent=body_style, fontSize=12, alignment=1)),
            Paragraph(f"<b>{score}</b>", ParagraphStyle("V7", parent=body_style, fontSize=12, textColor=status_color, alignment=1)),
        ]
    ]

    exec_table = Table(exec_grid_data, colWidths=[70, 70, 70, 70, 70, 75, 75])
    exec_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f1f5f9")),
        ('BACKGROUND', (0,1), (-1,1), colors.HexColor("#ffffff")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(exec_table)
    story.append(Spacer(1, 20))

    # --- 3. SEVERITY DISTRIBUTION ---
    story.append(Paragraph("2. Severity & Risk Distribution", h1_style))
    stat_rows = [
        [Paragraph("<b>Severity Level</b>", body_style), Paragraph("<b>Count</b>", body_style), Paragraph("<b>Impact Description</b>", body_style)],
        [Paragraph("<font color='#ef4444'><b>CRITICAL</b></font>", body_style), str(critical_cnt), Paragraph("Direct RCE, arbitrary code execution, or unauthenticated database access.", body_style)],
        [Paragraph("<font color='#f97316'><b>HIGH</b></font>", body_style), str(high_cnt), Paragraph("Command injection, SQL injection, exposed API tokens, or prototype pollution.", body_style)],
        [Paragraph("<font color='#eab308'><b>MEDIUM</b></font>", body_style), str(medium_cnt), Paragraph("XSS, weak hashing (MD5/SHA1), SSRF risks, or insecure temporary files.", body_style)],
        [Paragraph("<font color='#3b82f6'><b>LOW / INFO</b></font>", body_style), str(low_cnt), Paragraph("Code quality violations, assert statements, or configuration warnings.", body_style)]
    ]
    sev_table = Table(stat_rows, colWidths=[110, 60, 330])
    sev_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f8fafc")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(sev_table)
    story.append(Spacer(1, 20))

    # --- 4. DETAILED VULNERABILITY FINDINGS ---
    story.append(Paragraph("3. Vulnerability Findings", h1_style))
    
    if not vulnerabilities:
        story.append(Paragraph("No security vulnerabilities were identified in the target codebase.", body_style))
    else:
        sev_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
        sorted_vulns = sorted(vulnerabilities, key=lambda v: sev_order.get((v.severity or "INFO").upper(), 4))

        for idx, vuln in enumerate(sorted_vulns, 1):
            sev_str = (vuln.severity or "INFO").upper()
            sev_c = c_red if sev_str == "CRITICAL" else (c_orange if sev_str == "HIGH" else (c_yellow if sev_str == "MEDIUM" else c_blue))
            
            cwe_ref = "CWE-89 (SQLi)" if "sql" in (vuln.category or "").lower() else ("CWE-79 (XSS)" if "xss" in (vuln.category or "").lower() else ("CWE-78 (Cmd Inj)" if "command" in (vuln.category or "").lower() or "code" in (vuln.category or "").lower() else "CWE-200"))
            owasp_ref = "A03:2021-Injection" if "injection" in (vuln.category or "").lower() or "sql" in (vuln.category or "").lower() else "A01:2021-Broken Access Control"

            finding_p = Paragraph(f"<b>Finding #{idx}: {safe_escape(vuln.category)}</b>", ParagraphStyle("VT", parent=h2_style, textColor=c_text_dark))
            badge_p = Paragraph(f"<b>[{sev_str}]</b>", ParagraphStyle("VB", parent=body_style, textColor=sev_c, fontName="Helvetica-Bold", alignment=2))

            tbl_hdr = Table([[finding_p, badge_p]], colWidths=[400, 100])
            tbl_hdr.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'BOTTOM')]))
            story.append(tbl_hdr)

            vuln_meta_text = (
                f"<b>File:</b> {safe_escape(vuln.file_path)} (Line {vuln.line_number or 1})  •  "
                f"<b>Engine:</b> {safe_escape(vuln.tool_name)}  •  "
                f"<b>CWE:</b> {cwe_ref}  •  <b>OWASP:</b> {owasp_ref}<br/>"
                f"<b>Description:</b> {safe_escape(vuln.message)}"
            )
            story.append(Paragraph(vuln_meta_text, body_style))

            if vuln.code_snippet:
                story.append(Paragraph("<b>Vulnerable Code Snippet:</b>", body_style))
                story.append(XPreformatted(safe_escape(vuln.code_snippet), code_style))

            story.append(Paragraph(f"<b>Recommended Remediation:</b> {safe_escape(vuln.remediation)}", body_style))

            if vuln.ai_explanation:
                story.append(Paragraph("<b>AI Security Analysis & Remediation:</b>", ParagraphStyle("AIH", parent=body_style, fontName="Helvetica-Bold", textColor=c_cyan)))
                exp_clean = safe_escape(vuln.ai_explanation).replace("\n", "<br/>")
                story.append(Paragraph(exp_clean, body_style))

                if vuln.ai_fix:
                    story.append(Paragraph("<b>AI Secure Implementation Fix:</b>", body_style))
                    story.append(XPreformatted(safe_escape(vuln.ai_fix), code_style))

            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceBefore=8, spaceAfter=14))

    # --- 5. SECRET / CREDENTIAL FINDINGS ---
    story.append(PageBreak())
    story.append(Paragraph("4. Secret & Credential Audit", h1_style))
    if not secrets_list:
        story.append(Paragraph("No hardcoded secrets or exposed API credentials were found.", body_style))
    else:
        sec_rows = [[Paragraph("<b>Category</b>", body_style), Paragraph("<b>File</b>", body_style), Paragraph("<b>Line</b>", body_style), Paragraph("<b>Masked Value</b>", body_style)]]
        for s in secrets_list:
            sec_rows.append([
                Paragraph(safe_escape(s.category), body_style),
                Paragraph(safe_escape(s.file_path), body_style),
                str(s.line_number or 1),
                Paragraph(f"<font color='#ef4444'><code>{mask_secret(s.code_snippet)}</code></font>", body_style)
            ])
        sec_table = Table(sec_rows, colWidths=[130, 180, 40, 150])
        sec_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f8fafc")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(sec_table)
    story.append(Spacer(1, 20))

    # --- 6. DEPENDENCY SECURITY ---
    story.append(Paragraph("5. Dependency Security Analysis", h1_style))
    if not deps_list:
        story.append(Paragraph("All scanned package manifests (`package.json`, `requirements.txt`) match safe release baselines.", body_style))
    else:
        dep_rows = [[Paragraph("<b>Manifest</b>", body_style), Paragraph("<b>Finding</b>", body_style), Paragraph("<b>Severity</b>", body_style), Paragraph("<b>Remediation</b>", body_style)]]
        for d in deps_list:
            sev_c = c_red if (d.severity or "").upper() == "CRITICAL" else c_orange
            dep_rows.append([
                Paragraph(safe_escape(d.file_path), body_style),
                Paragraph(safe_escape(d.message), body_style),
                Paragraph(f"<b><font color='{sev_c.hexval()}'>{safe_escape(d.severity)}</font></b>", body_style),
                Paragraph(safe_escape(d.remediation), body_style)
            ])
        dep_table = Table(dep_rows, colWidths=[90, 190, 70, 150])
        dep_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f8fafc")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(dep_table)
    story.append(Spacer(1, 20))

    # --- 7. AI SECURITY INTELLIGENCE & REMEDIATION ---
    story.append(Paragraph("6. AI Security Intelligence & Priority Remediation", h1_style))
    ai_intel_text = (
        "<b>AI Risk Summary:</b> Automated reasoning engines synthesized findings against OWASP Top 10 guidelines.<br/>"
        "<b>Priority 1 (Immediate Fix):</b> Remediate critical RCE, hardcoded secrets, and SQL concatenations.<br/>"
        "<b>Priority 2 (Scheduled Sprint):</b> Replace weak hashing algorithms (MD5/SHA1) and upgrade vulnerable dependency versions.<br/>"
        "<b>Priority 3 (Hardening):</b> Enforce strict DOM input sanitization and configure environment secret managers."
    )
    story.append(Paragraph(ai_intel_text, body_style))
    story.append(Spacer(1, 20))

    # --- 8. SCANNER ENGINE RESULTS ---
    story.append(Paragraph("7. Scanner Engine Execution Status", h1_style))
    eng_rows = [
        [Paragraph("<b>Engine Name</b>", body_style), Paragraph("<b>Target Focus</b>", body_style), Paragraph("<b>Status</b>", body_style)],
        [Paragraph("<b>Gitleaks</b>", body_style), Paragraph("Hardcoded Secrets & Credential Detection", body_style), Paragraph("<font color='#10b981'><b>COMPLETED</b></font>", body_style)],
        [Paragraph("<b>Bandit AST</b>", body_style), Paragraph("Python Abstract Syntax Tree Security Analysis", body_style), Paragraph("<font color='#10b981'><b>COMPLETED</b></font>", body_style)],
        [Paragraph("<b>Semgrep SAST</b>", body_style), Paragraph("Multi-Language Pattern & Security Rule Engine", body_style), Paragraph("<font color='#10b981'><b>COMPLETED</b></font>", body_style)],
        [Paragraph("<b>Dependency Auditor</b>", body_style), Paragraph("Manifest CVE Vulnerability Matcher", body_style), Paragraph("<font color='#10b981'><b>COMPLETED</b></font>", body_style)],
        [Paragraph("<b>Ollama AI Intelligence</b>", body_style), Paragraph("Local LLM Defensive Remediation Engine", body_style), Paragraph("<font color='#10b981'><b>CONNECTED</b></font>", body_style)],
    ]
    eng_table = Table(eng_rows, colWidths=[150, 240, 110])
    eng_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f8fafc")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(eng_table)

    # Build PDF
    doc.build(story, canvasmaker=NumberedCanvas)
